#!/bin/bash

if [[ $(w | head -n1 |awk '{print$10}' | cut -d . -f1) -ge "1" ]]; then
	report=/var/log/sitrep/report$(date +%y%m%d-%H%M).log
	touch $report
	sitrep >> $report
else
#nothing
sleep 1
fi

